config/routes.rb
Rails.application.routes.draw do
  
devise_for :users, controllers: {
    sessions: 'sessions'
}
 
resources :users
root to: 'users#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
	
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  paginates_per 5

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
    
    validates :email, presence: true 
	validates :password, presence: true, length: { minimum: 6 }	
 	validates :password_confirmation, presence: true, length: { minimum: 6 }
      
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/sessions_controller.rb
class SessionsController < Devise::SessionsController
	
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  
  def index
    @users = User.all.page(params[:page])
  end

  def show
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      bypass_sign_in(@user)
      redirect_to ({ action: :show, id: @user }), notice: 'Амжилттай үүслээ.'
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @user.update(user_params)
      bypass_sign_in(@user)
      redirect_to ({ action: :show, id: @user }), notice: 'Нууц үг амжилттай солигдлоо.'
    else
      render :edit
    end
  end

  def destroy
    @user.destroy!
    redirect_to users_path, notice: 'Амжилттай устгалаа.'
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsDev</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/users/edit.html.erb
<h1>Хэрэглэгчийн мэйл: <%= current_user.email %></h1>
<!-- #edit.html.erb -->
<%= form_with model: @user, method: :patch, url: user_path, local: true do |form| %>
  <div class="mx-auto">
    <div class="form-group">
      <%= form.label :email ,class: "col-md-4 control-label"%>
      <div class="col-md-2">
        <%= form.email_field :email, class: 'form-control' %>
      </div>
    </div>

    <div class="form-group">
      <%= form.label :password,class: "col-md-4 control-label" %>
      <div class="col-md-2">
        <%= form.password_field :password, class: 'form-control' %>
      </div>
    </div>

    <div class="form-group">
      <%= form.label :password,class: "col-md-4 control-label" %>
      <div class="col-md-2">
        <%= form.password_field :password_confirmation, class: 'form-control' %>
      </div>
    </div>

    <div class="actions" style="padding-left:20px;">
      <%= form.submit 'Засварлах' , class: "btn btn-primary"%>
      <%= link_to "Буцах", :back , class: "btn btn-primary"%>
    </div>
  </div>
<% end %>

app/views/users/index.html.erb
<h1 style="margin-left: 20px;">Хэрэглэгчдийн жагсаалт</h1>
<div style="float: right; padding-right: 20px; margin:10px;">
<%= link_to 'Хэрэглэгч нэмэх', new_user_path, class: 'btn btn-primary'   %>
<%= link_to "Log out", destroy_user_session_path, method: :delete,class: 'btn btn-primary' %>
</div>

<table class="table table-striped ">
  <tr>
    <th>ID</th>
    <th>Email</th>
    <th>Created_at</th>
    <th colspan="3"></th>
  </tr>
 
  <% @users.each do |user| %>
    <tr>
      
      <td><%= user.id %></td>
      <td><%= user.email %></td>
      <td><%= user.created_at %></td>
      <td><%= link_to 'Show', user_path(user) %></td>
      <td><%= link_to 'Edit', edit_user_path(user) %></td>
      <td><%= link_to 'Destroy', user_path(user), method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>

<div style="margin-left: 10px;"><%= paginate @users %> </div>

app/views/users/new.html.erb
<h1>Шинэ хэрэглэгч:</h1>
<%= form_with model: @user, method: :post, url: users_path, local: true do |form| %>
 <div class="mx-auto">
    <div class="form-group">
      <%= form.label :email ,class: "col-md-4 control-label"%>
      <div class="col-md-2">
        <%= form.email_field :email, class: 'form-control' %>
      </div>
    </div>

    <div class="form-group">
      <%= form.label :password, class: "col-md-4 control-label" %>
      <div class="col-md-2">
        <%= form.password_field :password, class: 'form-control' %>
      </div>
    </div>

    <div class="form-group">
      <%= form.label :password, class: "col-md-4 control-label" %>
      <div class="col-md-2">
        <%= form.password_field :password_confirmation, class: 'form-control' %>
        </div>
    </div>

    <div class="actions" style="padding-left:20px;">
      <%= form.submit 'Нэмэх', class: "btn btn-primary" %>
      <%= link_to "Буцах", :back ,class: "btn btn-primary"%>
    </div>
  </div>
<% end %>

app/views/users/show.html.erb
<h3>Нэвтэрсэн хэрэглэгч:w <%= current_user.email %> </h3>
<table class="table table-info">
  <tr>
    <th>ID</th>
    <th>Email</th>
    <th>Created_at</th>
    <th>Updated_at</th>
    <th>SignInCount</th>
  </tr>
     <tr>
      <td><%= @user.id %></td>
      <td><%= @user.email %></td>
      <td><%= @user.created_at %></td>
      <td><%= @user.updated_at %></td>
      <td><%= @user.sign_in_count %></td>
  	</tr>	
</table>